import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://dev-amberg.seliselocal.com/login?go=/');
  await page.getByRole('button', { name: 'Login submit button' }).click();
  await page.getByRole('button', { name: 'Login submit button' }).click();
  await expect(page.getByRole('button', { name: 'New Project' })).toBeVisible();
  await page.getByRole('button', { name: 'New Project' }).click();
  await page.getByRole('textbox', { name: 'NameInput' }).click();
  await page.getByRole('textbox', { name: 'NameInput' }).fill('ADIF Metrico');
  await page.getByRole('textbox', { name: 'Number' }).click();
  await page.getByRole('textbox', { name: 'Number' }).fill('123456789');
  await page.getByRole('textbox', { name: 'Start Place' }).click();
  await page.getByRole('textbox', { name: 'Start Place' }).fill('a');
  await page.getByRole('textbox', { name: 'End Place' }).click();
  await page.getByRole('textbox', { name: 'End Place' }).fill('b');
  await page.getByRole('spinbutton', { name: 'Stationing Start TextField' }).click();
  await page.getByRole('spinbutton', { name: 'Stationing Start TextField' }).fill('100');
  await page.getByRole('spinbutton', { name: 'Stationing End TextField' }).click();
  await page.getByRole('spinbutton', { name: 'Stationing End TextField' }).fill('2000');
  await page.getByRole('textbox', { name: 'Comment' }).click();
  await page.getByRole('textbox', { name: 'Comment' }).fill('comment');
  await page.getByRole('radio', { name: 'Default' }).check();
  await page.getByRole('textbox', { name: 'Name of Line Section' }).click();
  await page.getByRole('textbox', { name: 'Name of Line Section' }).fill('Line section 1');
  await page.getByRole('textbox', { name: 'Name of Track' }).click();
  await page.getByRole('textbox', { name: 'Name of Track' }).fill('Track 1');
  await page.getByRole('combobox', { name: 'Select configuration template' }).click();
  await page.getByRole('option', { name: 'AdifMTrico1000Mm' }).click();
  await page.getByRole('combobox', { name: 'Select Template Option' }).click();
  await page.getByRole('option', { name: 'ADIF Métrico 1000 - Default' }).click();
  await page.getByRole('combobox', { name: 'Select Template Option ADIF M' }).click();
  await expect(page.getByRole('listbox')).toContainText('ADIF Métrico 1000 - Default');
  await expect(page.getByRole('listbox')).toContainText('ADIF Métrico 1000 - Generales');
  await page.getByRole('option', { name: 'ADIF Métrico 1000 - Default' }).click();
  await page.locator('input[name="CustomerInfo.Name"]').click();
  await page.locator('input[name="CustomerInfo.Name"]').fill('Company name 1');
  await page.locator('input[name="CustomerInfo.Street"]').click();
  await page.locator('input[name="CustomerInfo.Street"]').fill('a');
  await page.locator('input[name="CustomerInfo.Town"]').click();
  await page.locator('input[name="CustomerInfo.Town"]').fill('b');
  await page.locator('input[name="CustomerInfo.PostalCode"]').click();
  await page.locator('input[name="CustomerInfo.PostalCode"]').fill('12345');
  await page.locator('input[name="CustomerInfo.Region"]').click();
  await page.locator('input[name="CustomerInfo.Region"]').fill('c');
  await page.locator('[id="mui-component-select-CustomerInfo.Country"]').click();
  await page.getByRole('option', { name: 'American Samoa' }).click();
  await page.locator('input[name="CustomerInfo.PhoneNumber"]').click();
  await page.locator('input[name="CustomerInfo.PhoneNumber"]').fill('123456789');
  await page.locator('input[name="CustomerInfo.Email"]').click();
  await page.locator('input[name="CustomerInfo.Email"]').fill('example@gmail.com');
  await page.locator('input[name="ServiceProviderInfo.Name"]').click();
  await page.locator('input[name="ServiceProviderInfo.Name"]').fill('Service Provider name');
  await page.locator('input[name="ServiceProviderInfo.Street"]').click();
  await page.locator('input[name="ServiceProviderInfo.Street"]').fill('a');
  await page.locator('input[name="ServiceProviderInfo.Town"]').click();
  await page.locator('input[name="ServiceProviderInfo.Town"]').fill('b');
  await page.locator('input[name="ServiceProviderInfo.PostalCode"]').click();
  await page.locator('input[name="ServiceProviderInfo.PostalCode"]').fill('12345');
  await page.locator('input[name="ServiceProviderInfo.Region"]').click();
  await page.locator('input[name="ServiceProviderInfo.Region"]').fill('c');
  await page.getByLabel('', { exact: true }).click();
  await page.getByRole('option', { name: 'Albania' }).click();
  await page.locator('input[name="ServiceProviderInfo.PhoneNumber"]').click();
  await page.locator('input[name="ServiceProviderInfo.PhoneNumber"]').fill('123456789');
  await page.locator('input[name="ServiceProviderInfo.Email"]').click();
  await page.locator('input[name="ServiceProviderInfo.Email"]').fill('service.provider@gmai.com');
  await page.getByRole('button', { name: 'Custom Submit Button' }).click();
  await page.getByRole('textbox', { name: 'Search by Project Name' }).click();
  await page.getByRole('textbox', { name: 'Search by Project Name' }).fill('ADIF Metrico');
  await expect(page.getByLabel('ADIF Metrico')).toBeVisible();
});