import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://dev-amberg.seliselocal.com/login?go=/projects');
  await page.getByRole('button', { name: 'Login submit button' }).click();
  await page.getByRole('textbox', { name: 'Search by Project Name' }).click();
  await page.getByRole('textbox', { name: 'Search by Project Name' }).pressSequentially('Auto Inspection');
  await expect(page.getByLabel('#Auto Inspection')).toBeVisible();
  await page.getByLabel('#Auto Inspection').click();
  await page.getByTestId('line-section-tree-testid').getByText('line').click();
  await page.getByTestId('line-section-tree-testid-child-0').getByText('Track').click();
  await page.getByTestId('job-tree-testid').getByText('job').click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByTestId('job-tree-testid-child-0').getByRole('button').filter({ hasText: /^$/ }).click();
  const page1 = await page1Promise;
  await expect(page1.getByRole('heading')).toContainText('2024-02-23 18:00:02');
  await page1.getByRole('button', { name: 'filter-button' }).click();
  await expect(page1.getByTestId('chart-filter-section-drawer-test-id').getByRole('heading')).toContainText('Filter for Chart');
  await page1.getByLabel('select-all-parameters').getByRole('checkbox').check();
  await page1.getByLabel('select-all-parameters').getByRole('checkbox').uncheck();
  await expect(page1.getByRole('button', { name: 'Custom Submit Button' })).toBeVisible();
  await page1.getByRole('button', { name: 'Custom Submit Button' }).click();
  await expect(page1.getByLabel('chart-error-text')).toContainText('No chart data found');
  await page1.getByRole('button', { name: 'filter-button' }).click();
  await page1.getByRole('checkbox').nth(1).check();
  await page1.getByRole('button', { name: 'Custom Submit Button' }).click();
  await expect(page1.getByTestId('canvasjs-container')).toContainText('Gauge Defect - Nominal Gauge to Peak [mm]');
  await page1.getByRole('button', { name: 'filter-button' }).click();
  await page1.getByRole('checkbox').nth(1).uncheck();
  await page1.getByRole('checkbox').nth(2).check();
  await page1.getByRole('button', { name: 'Custom Submit Button' }).click();
  await expect(page1.getByTestId('canvasjs-container')).toContainText('Gauge Defect - Mean to Peak [mm]');
  await page1.getByRole('button', { name: 'full-screen-button' }).click();
  await expect(page1.locator('div').filter({ hasText: 'Charts20000.06Sample' }).nth(2)).toBeVisible();
  await expect(page1.getByText('Charts').nth(1)).toBeVisible();
  await expect(page1.getByRole('button', { name: 'new-tab-button' })).toBeVisible();
  await expect(page1.getByRole('button', { name: 'full-screen-button' })).toBeVisible();
  await expect(page1.getByRole('button', { name: 'next-button' })).toBeVisible();
  await expect(page1.getByRole('button', { name: 'prev-button' })).toBeVisible();
  await expect(page1.getByRole('button', { name: 'reload-button' })).toBeVisible();
});