import { test, expect } from '@playwright/test';

test('test @SUPPORT', async ({ page }) => {
  await page.goto('https://dev-amberg.seliselocal.com/login?go=/');
  await expect(page.getByRole('button', { name: 'Login submit button' })).toBeVisible();
  await page.getByRole('button', { name: 'Login submit button' }).click();
  await expect(page.getByRole('button', { name: 'Support' })).toBeVisible();
  await page.getByRole('button', { name: 'Support' }).click();
  await expect(page.getByRole('menuitem', { name: 'About' })).toBeVisible();
  await expect(page.getByRole('menuitem', { name: 'Contact Us' })).toBeVisible();
  await expect(page.getByRole('menuitem', { name: 'SSL Certificate' })).toBeVisible();
  await page.getByRole('menuitem', { name: 'Contact Us' }).click();
  await expect(page.locator('#customized-dialog-title')).toContainText('Contact Us');
  await expect(page.getByLabel('Contact Us')).toContainText('Amberg Technologies AG');
  await expect(page.getByLabel('Contact Us')).toContainText('Trockenloostrasse 21');
  await expect(page.getByLabel('Contact Us')).toContainText('8105 Regensdorf-Watt');
  await expect(page.getByLabel('Contact Us')).toContainText('Switzerland');
  await expect(page.getByRole('img', { name: 'logo' })).toBeVisible();
  await expect(page.getByLabel('Contact Us')).toContainText('Phone: +41 44 870 92 92');
  await expect(page.getByLabel('Contact Us')).toContainText('support.rail@amberg.ch');
  await expect(page.getByLabel('Contact Us')).toContainText('www.ambergrail.com');
  await page.getByRole('link', { name: 'support.rail@amberg.ch' }).click();
  await page.getByRole('link', { name: 'www.ambergrail.com' }).click();
  await expect(page.locator('#SgCookieOptin').getByText('Privacy settings')).toBeVisible();
  await page.goto('https://dev-amberg.seliselocal.com/projects');
  await page.getByRole('button', { name: 'Support' }).click();
  await page.getByRole('menuitem', { name: 'Contact Us' }).click();
  await expect(page.getByRole('button', { name: 'confirm' })).toBeVisible();
  await page.getByRole('button', { name: 'confirm' }).click();
});