export const languageData = {
  languageTitles: [
    "Language Settings",
    "Paramètres linguistiques",
    "Spracheinstellungen",
    "Impostazioni della lingua",
    "Ajustes de idioma",
    "Nastavení jazyka",
  ],

  languageFlow: [
    {
      optionLabel: "French",
      saveButton: "Save changes",
      expectedHeading: "Projets",
      menuItem: "Paramètres linguistiques",
      severity: [/Gravité 1/i, /Gravité 2/i, /Gravité 3/i],
      abbr: /Abréviation/i,
    },
    {
      optionLabel: "Allemand",
      saveButton: "Sauvegarder les changements",
      expectedHeading: "Projekte",
      menuItem: "Spracheinstellungen",
      severity: [/Schweregrad 1/i, /Schweregrad 2/i, /Schweregrad 3/i],
      abbr: /Abkürzung/i,
    },
    {
      optionLabel: "Italienisch",
      saveButton: "Änderungen speichern",
      expectedHeading: "Progetti",
      menuItem: "Impostazioni della lingua",
      severity: [/Gravità 1/i, /Gravità 2/i, /Gravità 3/i],
      abbr: /Abbreviazione/i,
    },
    {
      optionLabel: "Spagnolo",
      saveButton: "Salva le modifiche",
      expectedHeading: "Proyectos",
      menuItem: "Ajustes de idioma",
      severity: [/Gravedad 1/i, /Gravedad 2/i, /Gravedad 3/i],
      abbr: /Abreviatura/i,
    },
    {
      optionLabel: "Checa",
      saveButton: "Guardar los cambios",
      expectedHeading: "Projekty",
      menuItem: "Nastavení jazyka",
      severity: [/Závažnost 1/i, /Závažnost 2/i, /Závažnost 3/i],
      abbr: /Zkratka/i,
    },
    {
      optionLabel: "Angličtina",
      saveButton: "Uložit změny",
      expectedHeading: "Projects",
      menuItem: "Language Settings",
      severity: [/Severity 1/i, /Severity 2/i, /Severity 3/i],
      abbr: /Abbreviation/i,
    },
  ],
};
