import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await expect(page.getByTestId('edit-speed-section-drawer-test-id').getByRole('heading')).toContainText('Edit Speed');
  await expect(page.getByLabel('EditSpeedForm')).toContainText('Comment');
  await expect(page.getByLabel('EditSpeedForm')).toContainText('START LOCALIZATION [m]*');
  await expect(page.getByLabel('EditSpeedForm')).toContainText('END LOCALIZATION [m]*');
  await expect(page.getByLabel('EditSpeedForm')).toContainText('SPEED [km/h]*');
  await expect(page.getByRole('button', { name: 'Cancel' })).toBeVisible();
  await expect(page.getByText('Add Speed')).toBeVisible();
  await expect(page.getByText('Save changes')).toBeVisible();
  await page.getByText('Add Speed').click();
  await page.getByPlaceholder('Start Localization [m]*').click();
  await page.getByPlaceholder('Start Localization [m]*').fill('100');
  await page.getByPlaceholder('End Localization [m]*').click();
  await page.getByPlaceholder('End Localization [m]*').fill('200');
  await page.getByPlaceholder('Speed [km/h]*').click();
  await page.getByPlaceholder('Speed [km/h]*').fill('100');
  await page.getByText('Save changes').click();
  await expect(page.getByTestId('custom-side-bar')).toContainText('100.00');
  await expect(page.getByTestId('custom-side-bar')).toContainText('200.00');
  await expect(page.getByTestId('custom-side-bar')).toContainText('100.00');
  await page.getByRole('button', { name: 'Property Window Edit Button' }).click();
  await page.getByPlaceholder('Speed [km/h]*').click();
  await page.getByText('Add Speed').click();
  await page.locator('input[name="Elements.1.StationingEnd"]').fill('300');
  await page.locator('input[name="Elements.1.Speed"]').click();
  await page.locator('input[name="Elements.1.Speed"]').fill('500');
  await page.getByText('Save changes').click();
  await expect(page.getByLabel('EditSpeedForm')).toContainText('Please enter speed between 0 and 360.00 km/h');
});